"""Constants for the Askoheat integration."""

from datetime import timedelta
from typing import Final

DOMAIN: Final = "askoheat"

# Defaults
DEFAULT_SCAN_INTERVAL: Final = 5
SLOW_SCAN_INTERVAL: Final = timedelta(seconds=60)
HEARTBEAT_INTERVAL: Final = 30  # seconds

# Config keys
CONF_SCAN_INTERVAL: Final = "scan_interval"
CONF_SENSORS: Final = "sensors"

# Sentinel value for disconnected temperature sensors
SENSOR_DISCONNECTED_VALUE: Final = 9999.90
SENSOR_DISCONNECTED_TOLERANCE: Final = 0.01

# API endpoints
ENDPOINT_EMA: Final = "/GETEMA.JSON"
ENDPOINT_PAR: Final = "/GETPAR.JSON"
ENDPOINT_CON: Final = "/GETCON.JSON"
ENDPOINT_VAL: Final = "/GETVAL.JSON"
ENDPOINT_EXT: Final = "/GETEXT.JSON"
ENDPOINT_INT: Final = "/GETINT.JSON"
ENDPOINT_ALL: Final = "/GETALL.JSON"

# Number of temperature sensors
NUM_TEMP_SENSORS: Final = 6

# EMA register keys
EMA_STATUS: Final = "MODBUS_EMA_STATUS"
EMA_HEATER_LOAD: Final = "MODBUS_EMA_HEATER_LOAD"
EMA_SET_HEATER_STEP: Final = "MODBUS_EMA_SET_HEATER_STEP"
EMA_LOAD_SETPOINT_VALUE: Final = "MODBUS_EMA_LOAD_SETPOINT_VALUE"
EMA_LOAD_FEEDIN_VALUE: Final = "MODBUS_EMA_LOAD_FEEDIN_VALUE"
EMA_EMERGENCY_MODE: Final = "MODBUS_EMA_EMERGENCY_MODE"
EMA_HEAT_PUMP_REQUEST: Final = "MODBUS_EMA_HEAT_PUMP_REQUEST"
EMA_ANALOG_INPUT_FLOAT: Final = "MODBUS_EMA_ANALOG_INPUT_FLOAT"
EMA_STATUS_EXTENDED: Final = "MODBUS_EMA_STATUS_EXTENDED"
EMA_TEMP_SENSORS: Final = [
    f"MODBUS_EMA_TEMPERATURE_FLOAT_SENSOR{i}" for i in range(NUM_TEMP_SENSORS)
]

# PAR register keys
PAR_ID: Final = "MODBUS_PAR_ID"
PAR_TYPE: Final = "MODBUS_PAR_TYPE"
PAR_HEATER1_POWER: Final = "MODBUS_PAR_HEATER1_POWER"
PAR_HEATER2_POWER: Final = "MODBUS_PAR_HEATER2_POWER"
PAR_HEATER3_POWER: Final = "MODBUS_PAR_HEATER3_POWER"
PAR_ARTICLE_NUMBER: Final = "MODBUS_PAR_ARTICLE_NUMBER"
PAR_ARTICLE_NAME: Final = "MODBUS_PAR_ARTICLE_NAME"
PAR_SOFTWARE_VERSION: Final = "MODBUS_PAR_SOFTWARE_VERSION"
PAR_HARDWARE_VERSION: Final = "MODBUS_PAR_HARDWARE_VERSION"
PAR_NUMBER_OF_HEATER: Final = "MODBUS_PAR_NUMBER_OF_HEATER"
PAR_NUMBER_OF_STEPS: Final = "MODBUS_PAR_NUMBER_OF_STEPS"
PAR_MAX_POWER: Final = "MODBUS_PAR_MAX_POWER"

# CON register keys (writable)
CON_INPUT_SETTING: Final = "MODBUS_CON_INPUT_SETTING"
CON_RELAY_SEC_COUNT: Final = "MODBUS_CON_RELAY_SEC_COUNT"
CON_PUMP_SEC_COUNT: Final = "MODBUS_CON_PUMP_SEC_COUNT"
CON_AUTO_HEATER_OFF_MINUTES: Final = "MODBUS_CON_AUTO_HEATER_OFF_MINUTES"
CON_AUTO_HEATER_OFF_SETTING: Final = "MODBUS_CON_AUTO_HEATER_OFF_SETTING"
CON_CASCADE_PRIO: Final = "MODBUS_CON_CASCADE_PRIO"
CON_HEATBUFFER_TYPE: Final = "MODBUS_CON_HEATBUFFER_TYPE"
CON_HEATBUFFER_VOLUME: Final = "MODBUS_CON_HEATBUFFER_VOLUME"
CON_HEATER_POSITION: Final = "MODBUS_CON_HEATER_POSITION"
CON_LEGIO_SETTING: Final = "MODBUS_CON_LEGIO_SETTING"
CON_LEGIO_TEMPERATURE: Final = "MODBUS_CON_LEGIO_TEMPERATURE"
CON_LEGIO_HEATUP_MINUTES: Final = "MODBUS_CON_LEGIO_HEATUP_MINUTES"
CON_HOUSETYPE: Final = "MODBUS_CON_HOUSETYPE"
CON_HOUSEHOLD_MEMBERS: Final = "MODBUS_CON_HOUSEHOLD_MEMBERS"
CON_LOAD_FEEDIN_DELAY: Final = "MODBUS_CON_LOAD_FEEDIN_DELAY"
CON_LOAD_FEEDIN_BIAS: Final = "MODBUS_CON_LOAD_FEEDIN_BIAS"
CON_TIMEZONE_BIAS: Final = "MODBUS_CON_TIMEZONE_BIAS"
CON_SUMMERTIME_BIAS: Final = "MODBUS_CON_SUMMERTIME_BIAS"
CON_TEMPERATURE_HYSTERESIS: Final = "MODBUS_CON_TEMPERATURE_HYSTERESIS"
CON_TEMPERATURE_SETTING: Final = "MODBUS_CON_TEMPERATURE_SETTING"
CON_TEMPERATURE_MINIMUM: Final = "MODBUS_CON_TEMPERATURE_MINIMUM"
CON_TEMPERATURE_SET_HEATER_STEP: Final = "MODBUS_CON_TEMPERATURE_SET_HEATER_STEP"
CON_TEMPERATURE_LOAD_SETPOINT: Final = "MODBUS_CON_TEMPERATURE_LOAD_SETPOINT"
CON_TEMPERATURE_LOW_TARIFF: Final = "MODBUS_CON_TEMPERATURE_LOW_TARIFF"
CON_TEMPERATURE_HEAT_PUMP_REQUEST: Final = "MODBUS_CON_TEMPERATURE_HEAT_PUMP_REQUEST"
CON_HEAT_PUMP_REQUEST_OFF_STEP: Final = "MODBUS_CON_HEAT_PUMP_REQUEST_OFF_STEP"
CON_HEAT_PUMP_REQUEST_ON_STEP: Final = "MODBUS_CON_HEAT_PUMP_REQUEST_ON_STEP"
CON_EMERGENCY_MODE_ON_STEP: Final = "MODBUS_CON_EMERGENCY_MODE_ON_STEP"
CON_RTU_ENERGY_METER_TYPE: Final = "MODBUS_CON_RTU_ENERGY_METER_TYPE"
CON_ANALOG_IN_HYSTERESIS: Final = "MODBUS_CON_ANALOG_IN_HYSTERESIS"


# CON analog threshold keys (0-7)
def con_analog_threshold(index: int) -> str:
    return f"MODBUS_CON_ANALOG_IN_{index}_THRESHOLD"


def con_analog_threshold_step(index: int) -> str:
    return f"MODBUS_CON_ANALOG_IN_{index}_THRESHOLD_STEP"


def con_analog_threshold_temp(index: int) -> str:
    return f"MODBUS_CON_ANALOG_IN_{index}_THRESHOLD_TEMP"


# VAL register keys (read-only)
VAL_OPERATING_TIME: Final = "MODBUS_VAL_OPERATING_TIME"
VAL_OPERATING_HEATER1: Final = "MODBUS_VAL_OPERATING_HEATER1"
VAL_OPERATING_HEATER2: Final = "MODBUS_VAL_OPERATING_HEATER2"
VAL_OPERATING_HEATER3: Final = "MODBUS_VAL_OPERATING_HEATER3"
VAL_OPERATING_PUMP: Final = "MODBUS_VAL_OPERATING_PUMP"
VAL_RELAY1_COUNT: Final = "MODBUS_VAL_RELAY1_COUNT"
VAL_RELAY2_COUNT: Final = "MODBUS_VAL_RELAY2_COUNT"
VAL_RELAY3_COUNT: Final = "MODBUS_VAL_RELAY3_COUNT"
VAL_RELAY4_COUNT: Final = "MODBUS_VAL_RELAY4_COUNT"
VAL_STATUS: Final = "MODBUS_VAL_STATUS"
VAL_HEATER_LOAD: Final = "MODBUS_VAL_HEATER_LOAD"
VAL_ACTUAL_CONTROL_INPUT: Final = "MODBUS_VAL_ACTUAL_CONTROL_INPUT"
VAL_LEGIO_STATUS: Final = "MODBUS_VAL_LEGIO_STATUS"
VAL_ERROR_STATUS: Final = "MODBUS_VAL_ERROR_STATUS"
VAL_TEMPERATURE_STATUS: Final = "MODBUS_VAL_TEMPERATURE_STATUS"
VAL_BOOT_COUNT: Final = "MODBUS_VAL_BOOT_COUNT"
VAL_MAX_TEMPERATURE: Final = "MODBUS_VAL_MAX_TEMPERATURE"
VAL_ACTUAL_TEMPERATURE_LIMIT: Final = "MODBUS_VAL_ACTUAL_TEMPERATURE_LIMIT"
VAL_STATUS_EXTENDED: Final = "MODBUS_VAL_STATUS_EXTENDED"

# VAL operating hours per mode
VAL_OPERATING_SET_HEATER_STEP: Final = "MODBUS_VAL_OPERATING_SET_HEATER_STEP"
VAL_OPERATING_LOAD_SETPOINT: Final = "MODBUS_VAL_OPERATING_LOAD_SETPOINT"
VAL_OPERATION_LOAD_FEEDIN: Final = "MODBUS_VAL_OPERATION_LOAD_FEEDIN"
VAL_OPERATION_HEAT_PUMP_REQUEST: Final = "MODBUS_VAL_OPERATION_HEAT_PUMP_REQUEST"
VAL_OPERATION_ANALOG_IN: Final = "MODBUS_VAL_OPERATION_ANALOG_IN"
VAL_OPERATION_EMERGENCY_MODE: Final = "MODBUS_VAL_OPERATION_EMERGENCY_MODE"
VAL_OPERATION_LEGIO: Final = "MODBUS_VAL_OPERATION_LEGIO"
VAL_OPERATION_LOW_TARIFF: Final = "MODBUS_VAL_OPERATION_LOW_TARIFF"
VAL_OPERATION_MINIMAL_TEMP: Final = "MODBUS_VAL_OPERATION_MINIMAL_TEMP"

# VAL operating hours per heater step
VAL_OPERATING_HEATER_STEPS: Final = [
    f"MODBUS_VAL_OPERATING_HEATER_STEP_{i}" for i in range(1, 8)
]

# VAL usage counts per mode
VAL_SET_HEATER_STEP_COUNT: Final = "MODBUS_VAL_SET_HEATER_STEP_COUNT"
VAL_LOAD_SETPOINT_COUNT: Final = "MODBUS_VAL_LOAD_SETPOINT_COUNT"
VAL_LOAD_FEEDIN_COUNT: Final = "MODBUS_VAL_LOAD_FEEDIN_COUNT"
VAL_HEAT_PUMP_REQUEST_COUNT: Final = "MODBUS_VAL_HEAT_PUMP_REQUEST_COUNT"
VAL_ANALOG_IN_COUNT: Final = "MODBUS_VAL_ANALOG_IN_COUNT"
VAL_EMERGENCY_MODE_COUNT: Final = "MODBUS_VAL_EMERGENCY_MODE_COUNT"
VAL_LEGIO_COUNT: Final = "MODBUS_VAL_LEGIO_COUNT"
VAL_LOW_TARIFF_COUNT: Final = "MODBUS_VAL_LOW_TARIFF_COUNT"
VAL_MINIMAL_TEMP_COUNT: Final = "MODBUS_VAL_MINIMAL_TEMP_COUNT"

# EXT register keys (read-only)
EXT_STATUS: Final = "MODBUS_EXT_STATUS"
EXT_HEATER_LOAD: Final = "MODBUS_EXT_HEATER_LOAD"
EXT_LEGIO_STATUS: Final = "MODBUS_EXT_LEGIO_STATUS"
EXT_LOAD_SETPOINT_VALUE: Final = "MODBUS_EXT_LOAD_SETPOINT_VALUE"
EXT_LOAD_FEEDIN_VALUE: Final = "MODBUS_EXT_LOAD_FEEDIN_VALUE"
EXT_TEMP_SENSORS: Final = [
    f"MODBUS_EXT_TEMPERATURE_FLOAT_SENSOR{i}" for i in range(5)
]
EXT_ANALOG_INPUT_FLOAT: Final = "MODBUS_EXT_ANALOG_INPUT_FLOAT"

# CMD register keys (write-only)
CMD_SET_HEATER_STEP: Final = "MODBUS_CMD_SET_HEATER_STEP"
CMD_LOAD_SETPOINT_VALUE: Final = "MODBUS_CMD_LOAD_SETPOINT_VALUE"
CMD_LOAD_FEEDIN_VALUE: Final = "MODBUS_CMD_LOAD_FEEDIN_VALUE"
CMD_RESET: Final = "MODBUS_CMD_RESET"
CMD_RECONFIG: Final = "MODBUS_CMD_RECONFIG"
CMD_IDENTIFY: Final = "MODBUS_CMD_IDENTIFY"
CMD_CLEAR_TEMP_SENSOR_ERROR: Final = "MODBUS_CMD_CLEAR_TEMP_SENSOR_ERROR"

# CON_INPUT_SETTING bit flags
INPUT_SETTING_ANALOG: Final = 0x01
INPUT_SETTING_HEAT_PUMP: Final = 0x02
INPUT_SETTING_EMERGENCY: Final = 0x04
INPUT_SETTING_SETPOINT: Final = 0x08
INPUT_SETTING_FEEDIN: Final = 0x10

# Status bit flags (low byte)
STATUS_RELAY1: Final = 0x01
STATUS_RELAY2: Final = 0x02
STATUS_RELAY3: Final = 0x04
